<template>
  <div
    class="margin col-md-6 col-lg-6 col-sm-12 col-xs-12 justify-center content-center items-center"
  >
    <div class="text-h2 q-pb-xl text-center">Privacy</div>
    <div>Privacy policy</div>
    <p>
      Personal integrity, trust and respect are at the core of our value. That
      is why we created this GDPR-compliant policy to disclose fully
      transparently how we collect your personal information when you use our
      service, what rights you have and how you can use them under the EU GDPR.
      We only collect what we need in order to support you with and improve our
      Service for you.
    </p>
    <p>
      We hope this gives a clear picture of the measurements we take to ensure
      your data privacy on top of the technology infrastructure which keeps your
      data safe and secure. If you have more questions about data privacy, you
      can always contact us at
      <span class="text-accent1">hello@bocapital.se</span>
    </p>
    <q-space />

    <div>
      Why do we collect?
    </div>
    <p>
      We collect above information for various purposes to provide, fulfill and
      improve our Service to you including but not limited to: i) provide and
      maintain our Service, ii) verify your identify or manage your account,
      iii) contact or notify you, iv) enable you to use interactive tools of our
      Service, v) to provide customer support, vi) to fulfill our legal
      obligations, vii) to gather analysis and insights so that we can improve
      our Service, viii) monitor the usage of our Service, ix) detect, prevent
      and address technical issue, x) provide you with service updates, news or
      other general information
    </p>

    <q-space />

    <div>What information do we collect?</div>
    <p>
      <strong> Personal Data</strong> means personally identifiable information
      we receive it directly or indirectly from you, including but not limited
      to for example name, date of birth, social security number, address,
      e-mail, mobile phone number etc.
    </p>
    <p>
      <strong> Usage Data</strong> is data collected automatically either
      generated by the use of the Service or from the Service infrastructure
      itself, including but not limited to for example IP address, device type,
      operating system, platform, visited pages of our Service, time and
      duration of your visit etc.
    </p>
    <p>
      <strong> Cookies</strong> and similar tracking techniques are used to be
      able to deliver a better user experience. You can instruct your browser to
      refuse cookies but you would not be able to use some portions of our
      Service.
    </p>

    <q-space />

    <div>Who process your information?</div>
    <p>
      BoyangCapital AB, org.no 559224-4627 ("BoCapital","we", "us", or "our")
      operating the
      <span class="text-accent1">www.bocapital.se</span> website ("Service") are
      responsible to determine the purposes for which and the manner in which
      any personal data are or are to be processed.
    </p>
    <p>
      We may employ third party companies and individuals to facilitate our
      Service ("Service Providers"), to provide the Service on our behalf, to
      perform Service-related services or to assist us in analyzing how our
      Service is used. We may use the services of various Service Providers in
      order to process your data more effectively. These third parties may have
      access to your Personal Data only to perform these tasks on our behalf and
      are obligated not to disclose or use it for any other purpose.
    </p>
    <p>
      Additionally, our Service contain links to other sites that are not
      operated by us. Our privacy policy applies only to our website, so if you
      click on a third party link, you will be directed to that third party's
      site and we strongly recommend you to review the privacy policy of every
      site you visit. We have no control over hence no responsibility for the
      content, privacy policies or practices of any third party sites or
      services.
    </p>
    <q-space />

    <div>How do we process your information?</div>
    <p>
      All personal information about you that we process for the Service is
      securely stored on Amazon Web Services (further info of AWS Cloud Security
      can be read on https://aws.amazon.com/security/)
    </p>
    <p>
      We retain your Personal Data only for as long as is necessary for the
      above purposes to fulfill our Service. We will retain and use your
      Personal Data to the extent necessary to comply with our legal
      obligations, resolve disputes, and enforce our legal agreements and
      policies. Under certain circumstances, we are required to disclose your
      Personal Data if required to do so by law or in response to valid requests
      by public authorities (e.g. a court or a government authority).
    </p>
    <p>
      We store Usage Data for internal analysis purposes. Usage Data is
      generally retained for a shorter period of time, except when this data is
      used to strengthen the security or to improve the functionality of our
      Service, or we are legally obligated to retain this data for longer time
      periods.
    </p>
    <p>
      We will take all measurements reasonably necessary to ensure that your
      data is treated securely and in accordance with this Privacy Policy and no
      transfer of your Personal Data will take place to an organization or a
      country unless there are adequate controls in place including the security
      of your data and other personal information. You can always request
      information about the appropriate protection measures that have been taken
      if the Personal Data is transferred to a country outside the EU or EEA.
    </p>
    <q-space />

    <div>What are your data protection rights?</div>
    <p>
      Your data is always you. You have the right to view, correct, delete or
      request processing restriction of your Personal Data. Specially, this
      means you have the right to: i) freely access your Personal Data stored by
      us, ii) correct incorrect or incomplete information about yourself, iii)
      request us to correct or complete your personal information, iv) request
      the deletion of Personal Data under certain conditions if these are no
      longer necessary for the purpose for which they were collected (however
      there may be legal obligations that prevent us from immediately deleting
      parts of your personal data. In such a case, we save the personal data we
      are obliged to save and block it from being used for purposes other than
      to fulfill our legal obligations).
    </p>
    <p>
      We would like to send you information about our services that we think you
      might like. You have the right at any time to unsubscribe from our emails
      related to service update, news or other general information.
    </p>
    <p>
      By using the Service, you agree to the collection and use of information
      in accordance with this policy. The provision of personal data is part of
      a statutory and contractual requirements and legal obligations of our
      Service, legal agreements and policies - the possible consequences of
      failing to provide the correct and complete personal data can be not able
      to use our Service.
    </p>

    <q-space />
    <div>Get in touch</div>
    <p>
      If you have any questions about this Privacy Policy, you can always get in
      touch with us via
      <span class="text-accent1">hello@bocapital.se.</span>
    </p>
    <p>
      Unless otherwise defined in this Privacy Policy, terms used in this
      Privacy Policy have the same meanings as in our Terms, accessible from
      <span class="text-accent1">www.bocapital.se.</span>
    </p>
  </div>
</template>

<style lang="sass" scoped>
.margin
  margin: 50px 300px 50px 300px
div
  font-size: 24px
  color: $accent
p
  font-size: 16px
  color: $primary
.text-accent1
  color: $accent
@media only screen and (max-width: 1200px)
  .margin
    margin: 20px 20px 20px 20px
@media only screen and (max-width: 767px)
  .margin
    margin: 15px 5px 15px 5px !important
    padding: 0px 0px 0px 0px
</style>
